### PR TITLE
Add fact counter

### LINKED ISSUE #34: Add Counter to Facts
Replace the wording on each fact from one in four facts to x of y facts.
Where x = fact number (counter) and y = total facts.

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #34 

Adds a counter to each fact.
Changes the weight on each fact so fact 1 is first, then 2 etc...
This adds weight front matter to each fact to keep them in the correct order (Hugo does it by date added first).
screen shot 2018-12-30 at 2 38 55 pm

### CODE REVIEW

**Comment by andybroomfield** [comment]
@jt-nti byTitle is for the page title not the file name, I've not been able to get `{{ range .Pages.ByParam ".File.BaseFileName" }}` to order correctly.

**Comment by jt-nti** [comment]
@andybroomfield were you trying to get the fact1, fact2 URLs to show up in numeric order? I'd rather keep things ordered by title which, despite the defaults mentioned in the doc, is what they seemed to be. I've created pull request #38 to make that order explicit which I'll publish later unless anyone objects.

The numbers in the URLs showing up out of order does look a bit odd but those file names were just me being very unimaginative! I'd rather change the fact .md file names to something more meaningful if the permalink number ordering needs fixing, especially now there's a 404 page.

**Comment by andybroomfield** [comment]
@jt-nti Yes thats right, trying to correct the order of fact1, fact2 etc...
I'll leave it in your hands if that what you wish to do.
In future, it may be worth using weight to have more prominent facts first on list, though thats a discussion for another time once a copy writer has had a look through them.

**Comment by jt-nti** [comment]
@andybroomfield OK, makes sense now. Weights would definitely be the right way to highlight particular facts or to have complete control over ordering, e.g. for the help pages. The downside is that I think adding too much front matter makes it more unfriendly for non-developers, especially page ordering with weight, e.g. adding a new page in the middle could be awkward with sequential numbers which is why the help pages have weights in 10s. That's probably worse for facts which are more likely to be created by a non-developer, as opposed to just editing the content of existing help pages. Definitely worth revisiting though, and could be influenced by any requirement for the same facts to appear under different subjects. I'll get #38 in and we can have a chat with Jon when h's back around. Thanks very much for figuring out the fact numbers.

**Pull request closed without merging**
